.PHONY : clean

clean :
	find . -type f \
	-not -name 'C1input' \
	-not -name 'input' \
	-not -name 'batchjob.*' \
	-not -name 'vmec_out.nc' \
	-not -name 'options_bjacobi1' \
	-not -name 'makefile' \
	-delete
